### ISSUE TITLE
new question

### ISSUE THREAD

**Issue by Ystartff** [Yuanhaojun513/MMUNet#2]
Author, I found that your expansion corrosion is not described in enough detail in the paper, can you please describe your method in detail?

**Comment by Yuanhaojun513** [comment]
![膨胀](https://github.com/Yuanhaojun513/MMUNet/assets/94043664/90c881af-afa4-4934-8c87-9a04292b19c0)

**Comment by Yuanhaojun513** [comment]
![erode](https://github.com/Yuanhaojun513/MMUNet/assets/94043664/5abebbcf-de34-4609-989c-04f72bd788f4)

**Comment by Yuanhaojun513** [comment]
![腐蚀](https://github.com/Yuanhaojun513/MMUNet/assets/94043664/107989db-6616-4048-8728-3610c4c075c3)

**Comment by Yuanhaojun513** [comment]
look this photo

**Comment by Ystartff** [comment]
I think you should describe your training process in detail and refine your readme file
